# Remove 'version:' to silence the warning if you’d like.
services:
  classifier:
    build: ./agent_core
    ports:
      - "8000:8000"

  concierge:
    build: ./web_demo
    environment:
      - CLASSIFIER_URL=http://classifier:8000
    depends_on:
      - classifier
    ports:
      - "8501:8501"
